### ISSUE TITLE
Reach out to upstreams about verification

### ISSUE THREAD

**Issue by barthalion** [flathub-infra/website#1253]
I've had a quick glance over the popular section and these apps are maintained by upstream, but are not verified yet. We should ask respective teams to verify their ownership:

- [x] org.libretro.RetroArch https://github.com/flathub/org.libretro.RetroArch/issues/247
- [ ] org.ppsspp.PPSSPP (we never transferred the repo to the team, but they link to Flathub on their website)
- [x] org.citra_emu.citra https://github.com/flathub/org.citra_emu.citra/issues/389
- [x] net.davidotek.pupgui2 https://github.com/flathub/net.davidotek.pupgui2/issues/12
- [x] io.github.shiiion.primehack
- [x] net.lutris.Lutris https://github.com/flathub/net.lutris.Lutris/issues/323
- [x] com.mattjakeman.ExtensionManager https://github.com/flathub/com.mattjakeman.ExtensionManager/issues/13
- [x] org.onlyoffice.desktopeditors https://github.com/flathub/org.onlyoffice.desktopeditors/issues/95
- [x] org.yuzu_emu.yuzu https://github.com/flathub/org.yuzu_emu.yuzu/issues/973
- [x] org.x.Warpinator (This domain seems wrong? Not sure why we accepted it that way)
- [ ] io.gitlab.librewolf-community (It's unclear to me if it's maintained by upstream or not)
- [ ] ~~net.brinkervii.grapejuice~~ (It's not upstream-maintained: https://gitlab.com/brinkervii/grapejuice/-/issues/434#note_1310309123)
- [x] org.remmina.Remmina https://github.com/flathub/org.remmina.Remmina/issues/177
- [x] org.fedoraproject.MediaWriter https://github.com/flathub/org.fedoraproject.MediaWriter/issues/21
- [x] ~~io.mrarm.mcpelauncher~~ (I guess we shouldn't mark third party Minecraft launcher as verified after all)
- [x] tv.plex.PlexDesktop
- [x] net.retrodeck.retrodeck https://github.com/flathub/net.retrodeck.retrodeck/issues/145
- [x] com.plexamp.Plexamp https://github.com/flathub/com.plexamp.Plexamp/issues/40
- [x] tv.plex.PlexHTPC
- [x] fr.handbrake.ghb https://github.com/HandBrake/HandBrake/issues/5037
- [x] com.github.iwalton3.jellyfin-media-player https://github.com/flathub/com.github.iwalton3.jellyfin-media-player/issues/13
- [x] org.ryujinx.Ryujinx https://github.com/flathub/org.ryujinx.Ryujinx/issues/45
- [x] GIMP https://github.com/flathub/org.gimp.GIMP/issues/204

**Comment by SirMangler** [comment]
I can confirm `io.github.shiiion.primehack` is the official flatpak for PrimeHack. 

My creds as one of of the two lead devs:
<https://github.com/shiiion/dolphin/commits?author=SirMangler>
<https://github.com/shiiion/dolphin/releases/tag/1.0.5>
<https://github.com/shiiion/dolphin/wiki/Frequently-Asked-Questions#what-platforms-is-primehack-on>

**Comment by barthalion** [comment]
@SirMangler Thanks, I will mark PrimeHack as verified by staff.

**Comment by barthalion** [comment]
Hey @Mousa, poking you here as tv.plex.PlexDesktop and tv.plex.PlexHTPC don't have issues enabled. Could you log in at https://beta.flathub.org and verify both IDs? It will generate a token for each to be uploaded at a specific location of `plex.tv`. They are marked as verified manually now, but it will disappear next upgrade.
